app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases')), name='bases'),
    path('inv/', include(('inv.urls', 'inv')), name='inv'),
    path('admin/', admin.site.urls)
]

inv/urls.py
from django.urls import path
from .views import CategoryNew, CategoryEdit, CategoryView, CategoryDelete, SubCategoryView, SubCategoryNew, SubCategoryEdit, SubCategoryDelete, MarcaView, MarcaEdit, MarcaNew, marca_inactivar, UMView, UMNew, UMEdit, um_inactivar, ProductosView, ProductoNew

urlpatterns = [
    path('categories/', CategoryView.as_view(), name='categories_list'),
    path('categories/new', CategoryNew.as_view(), name='category_new'),
    path('categories/edit/<int:pk>', CategoryEdit.as_view(), name='category_edit'),
    path('categories/delete/<int:pk>',
         CategoryDelete.as_view(), name='category_del'),

    path('subcategories/', SubCategoryView.as_view(), name='subcategories_list'),
    path('subcategories/new', SubCategoryNew.as_view(), name='subcategory_new'),
    path('subcategories/edit/<int:pk>',
         SubCategoryEdit.as_view(), name='subcategory_edit'),
    path('subcategories/delete/<int:pk>',
         SubCategoryDelete.as_view(), name='subcategory_del'),

    path('marcas/', MarcaView.as_view(), name='marcas_list'),
    path('marca/new', MarcaNew.as_view(), name='marca_new'),
    path('marca/edit/<int:pk>',
         MarcaEdit.as_view(), name='marca_edit'),
    path('marca/inactivar/<int:id>',
         marca_inactivar, name='marca_inactivar'),


    path('um/', UMView.as_view(), name='um_list'),
    path('um/new', UMNew.as_view(), name='um_new'),
    path('um/edit/<int:pk>',
         UMEdit.as_view(), name='um_edit'),
    path('um/inactivar/<int:id>',
         um_inactivar, name='um_inactivar'),

    path('productos/', ProductosView.as_view(), name='productos_list'),
    path('producto/new', ProductoNew.as_view(), name='producto_new'),
]

bases/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class ClaseModelo(models.Model):
    status = models.BooleanField(default=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    user_create = models.ForeignKey(User, on_delete=models.CASCADE)
    user_update = models.IntegerField(blank=True, null=True)

    class Meta:
        abstract = True

inv/models.py
from django.db import models
from bases.models import ClaseModelo

# Create your models here.


class Category(ClaseModelo):
    description = models.CharField(
        max_length=100,
        help_text='Descripcion de la Categoria',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.description)

    def save(self):
        self.description = self.description.upper()
        super(Category, self).save()

    class Meta:
        verbose_name_plural = "Categories"


class SubCategory(ClaseModelo):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.CharField(
        max_length=100,
        help_text='Descripcion de la Categoria'
    )

    def __str__(self):
        return '{}:{}'.format(self.category.description, self.description)

    def save(self):
        self.description = self.description.upper()
        super(SubCategory, self).save()

    class Meta:
        verbose_name_plural = "Sub Categorias"
        unique_together = ('category', 'description')


class Marca(ClaseModelo):
    description = models.CharField(
        max_length=100,
        help_text='Descripcion de la Marca'
    )

    def __str__(self):
        return '{}'.format(self.description)

    def save(self):
        self.description = self.description.upper()
        super(Marca, self).save()

    class Meta:
        verbose_name_plural = "Marcas"


class UnidadMedida(ClaseModelo):
    description = models.CharField(
        max_length=100,
        help_text='Unidad de Medida'
    )

    def __str__(self):
        return '{}'.format(self.description)

    def save(self):
        self.description = self.description.upper()
        super(UnidadMedida, self).save()

    class Meta:
        verbose_name_plural = "Unidades de Medidad"


class Producto(ClaseModelo):
    codigo = models.CharField(
        max_length=20,
        unique=True
    )
    codigo_barras = models.CharField(
        max_length=50)
    descripcion = models.CharField(
        max_length=200,
    )
    precio = models.FloatField(default=0)
    existencia = models.IntegerField(default=0)
    ultima_compra = models.DateField(null=True, blank=True)

    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    unidad_medida = models.ForeignKey(UnidadMedida, on_delete=models.CASCADE)
    subcategoria = models.ForeignKey(SubCategory, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto, self).save()

    class Meta:
        verbose_name_plural = "Productos"
        unique_together = ('codigo', 'codigo_barras')

inv/forms.py
from django import forms
from .models import Category, SubCategory, Marca, UnidadMedida, Producto


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['description', 'status']
        labels = {'description': 'Descripciòn de la Categoria',
                  'status': 'Estatus'}
        widgets = {'description': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class SubCategoryForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        queryset=Category.objects.filter(status=True).order_by('description')
    )

    class Meta:
        model = SubCategory
        fields = ['category', 'description', 'status']
        labels = {'description': 'Sub-Categoria',
                  'status': 'Estatus'}
        widgets = {'description': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['category'].empty_label = "Selecione Categoria"


class MarcaForm(forms.ModelForm):

    class Meta:
        model = Marca
        fields = ['description', 'status']
        labels = {'description': 'Marca',
                  'status': 'Estatus'}
        widgets = {'description': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class UMForm(forms.ModelForm):

    class Meta:
        model = UnidadMedida
        fields = ['description', 'status']
        labels = {'description': 'Unidad de Medida',
                  'status': 'Estatus'}
        widgets = {'description': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class ProductoForm(forms.ModelForm):

    class Meta:
        model = Producto
        fields = ['codigo', 'codigo_barras', 'descripcion', 'status', 'precio', 'existencia', 'ultima_compra',
                  'marca', 'subcategoria', 'unidad_medida']
        widgets = {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['ultima_compra'].widget.attrs['readonly'] = True
        self.fields['existencia'].widget.attrs['readonly'] = True

inv/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse_lazy
from .models import Category, SubCategory, Marca, UnidadMedida, Producto
from .forms import CategoryForm, SubCategoryForm, MarcaForm, UMForm, ProductoForm

# Create your views here.


class CategoryView(LoginRequiredMixin, generic.ListView):
    model = Category
    template_name = 'inv/categories_list.html'
    context_object_name = 'obj'
    login_url = 'bases:login'


class CategoryNew(LoginRequiredMixin, generic.CreateView):
    model = Category
    template_name = "inv/category_form.html"
    context_object_name = "obj"
    form_class = CategoryForm
    success_url = reverse_lazy("inv:categories_list")
    login_url = "base:login"

    def form_valid(self, form):
        form.instance.user_create = self.request.user
        return super().form_valid(form)


class CategoryEdit(LoginRequiredMixin, generic.UpdateView):
    model = Category
    template_name = "inv/category_form.html"
    context_object_name = "obj"
    form_class = CategoryForm
    success_url = reverse_lazy("inv:categories_list")
    login_url = "base:login"

    def form_valid(self, form):
        form.instance.user_update = self.request.user.id
        return super().form_valid(form)


class CategoryDelete(LoginRequiredMixin, generic.DeleteView):
    model = Category
    template_name = 'inv/catalogos_del.html'
    context_object_name = 'obj'
    success_url = reverse_lazy('inv:categories_list')


class SubCategoryView(LoginRequiredMixin, generic.ListView):
    model = SubCategory
    template_name = 'inv/subcategories_list.html'
    context_object_name = 'obj'
    login_url = 'bases:login'


class SubCategoryNew(LoginRequiredMixin, generic.CreateView):
    model = SubCategory
    template_name = "inv/subcategory_form.html"
    context_object_name = "obj"
    form_class = SubCategoryForm
    success_url = reverse_lazy("inv:subcategories_list")
    login_url = "base:login"

    def form_valid(self, form):
        form.instance.user_create = self.request.user
        return super().form_valid(form)


class SubCategoryEdit(LoginRequiredMixin, generic.UpdateView):
    model = SubCategory
    template_name = "inv/subcategory_form.html"
    context_object_name = "obj"
    form_class = SubCategoryForm
    success_url = reverse_lazy("inv:subcategories_list")
    login_url = "base:login"

    def form_valid(self, form):
        form.instance.user_update = self.request.user.id
        return super().form_valid(form)


class SubCategoryDelete(LoginRequiredMixin, generic.DeleteView):
    model = SubCategory
    template_name = 'inv/catalogos_del.html'
    context_object_name = 'obj'
    success_url = reverse_lazy('inv:subcategories_list')


class MarcaView(LoginRequiredMixin, generic.ListView):
    model = Marca
    template_name = 'inv/marcas_list.html'
    context_object_name = 'obj'
    login_url = 'bases:login'


class MarcaNew(LoginRequiredMixin, generic.CreateView):
    model = Marca
    template_name = "inv/marca_form.html"
    context_object_name = "obj"
    form_class = MarcaForm
    success_url = reverse_lazy("inv:marcas_list")
    login_url = "base:login"

    def form_valid(self, form):
        form.instance.user_create = self.request.user
        return super().form_valid(form)


class MarcaEdit(LoginRequiredMixin, generic.UpdateView):
    model = Marca
    template_name = "inv/marca_form.html"
    context_object_name = "obj"
    form_class = MarcaForm
    success_url = reverse_lazy("inv:marcas_list")
    login_url = "base:login"


def marca_inactivar(request, id):
    marca = Marca.objects.filter(pk=id).first()
    contexto = {}
    template_name = 'inv/catalogos_del.html'

    if not marca:
        return redirect('inv:marcas_list')

    if request.method == 'GET':
        contexto = {'obj': marca}

    if request.method == 'POST':
        marca.status = False
        marca.save()
        return redirect('inv:marcas_list')

    return render(request, template_name, contexto)


class UMView(LoginRequiredMixin, generic.ListView):
    model = UnidadMedida
    template_name = 'inv/um_list.html'
    context_object_name = 'obj'
    login_url = 'bases:login'


class UMNew(LoginRequiredMixin, generic.CreateView):
    model = UnidadMedida
    template_name = "inv/um_form.html"
    context_object_name = "obj"
    form_class = UMForm
    success_url = reverse_lazy("inv:um_list")
    login_url = "base:login"

    def form_valid(self, form):
        form.instance.user_create = self.request.user
        return super().form_valid(form)


class UMEdit(LoginRequiredMixin, generic.UpdateView):
    model = UnidadMedida
    template_name = "inv/um_form.html"
    context_object_name = "obj"
    form_class = UMForm
    success_url = reverse_lazy("inv:um_list")
    login_url = "base:login"


def um_inactivar(request, id):
    um = UnidadMedida.objects.filter(pk=id).first()
    contexto = {}
    template_name = 'inv/catalogos_del.html'

    if not um:
        return redirect('inv:um_list')

    if request.method == 'GET':
        contexto = {'obj': um}

    if request.method == 'POST':
        um.status = False
        um.save()
        return redirect('inv:um_list')

    return render(request, template_name, contexto)


class ProductosView(LoginRequiredMixin, generic.ListView):
    model = Producto
    template_name = 'inv/productos_list.html'
    context_object_name = 'obj'
    login_url = 'bases:login'


class ProductoNew(LoginRequiredMixin, generic.CreateView):
    model = Producto
    template_name = "inv/producto_form.html"
    context_object_name = "obj"
    form_class = ProductoForm
    success_url = reverse_lazy("inv:productos_list")
    login_url = "base:login"

    def form_valid(self, form):
        form.instance.user_create = self.request.user
        return super().form_valid(form)

inv/templates/inv/catalogos_del.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                            Eliminar {{ obj.description }}</div>
                        <button type="submit" class="btn btn-danger"><i
                                class="far fa-question-circle"></i>Eliminar</button>
                        <!-- <a href=" {% url 'inv:categories_list' %}" class="btn btn-success"><span
                                class="fa fa-undo"></span>Cancelar</a> -->
                        <a href=" {{ request.META.HTTP_REFERER }}" class="btn btn-success"><span
                                class="fa fa-undo"></span>Cancelar</a>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-question-circle fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock page_content %}

{% block js_page %}
{% endblock js_page %}

inv/templates/inv/category_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
            <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if obj %} Editar {% else %} Nueva {% endif %} Categoria </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col-10">
                                    <div class="input-group">
                                        <input type="text" name="description" maxlength="100" class="form-control"
                                            required id="id_description" placeholder="Descripciòn"
                                            value="{% if obj %} {{obj.description}} {% endif %}">
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="form-group">
                                        <label for="id_status">Estatus</label>
                                        <input type="checkbox" name="status" class="form-control" id="id_status" 
                                        {% if obj.status %} checked {% endif %}>
                                    </div>
                                </div>
                                <!-- {{ form.as_p }} -->
                            </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col">
                                    <button type="submit" class="btn btn-danger"><span
                                            class="fa fa-save"></span>Guardar</button>
                                    <a href=" {% url 'inv:categories_list' %}" class="btn btn-success"><span
                                            class="fa fa-undo"></span>Cancelar</a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
</form>
{% endblock page_content %}

{% block js_page %}
{% endblock js_page %}

inv/templates/inv/marca_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-12 col-md-12 mb-12">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
            {% else %}
            <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if obj %} Editar {% else %} Nueva {% endif %} Marca </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col-10">
                                    <div class="input-group">
                                        <!-- <input type="text" name="description" maxlength="100" class="form-control"
                                            required id="id_description" placeholder="Descripciòn"
                                            value="{% if obj %} {{obj.description}} {% endif %}"> -->
                                        {{ form.description }}
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="input-group">
                                        <!-- <label for="id_status">Estatus</label>
                                        <input type="checkbox" name="status" class="form-control" id="id_status" 
                                        {% if obj.status %} checked {% endif %}> -->
                                        {{ form.status }}
                                    </div>
                                </div>
                                <!-- {{ form.as_p }} -->
                            </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col">
                                    <button type="submit" class="btn btn-danger"><span
                                            class="fa fa-save"></span>Guardar</button>
                                    <a href=" {% url 'inv:subcategories_list' %}" class="btn btn-success"><span
                                            class="fa fa-undo"></span>Cancelar</a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
</form>
{% endblock page_content %}

{% block js_page %}
{% endblock js_page %}

inv/templates/inv/producto_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-12 col-md-12 mb-12">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
            {% else %}
            <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if obj %} Editar {% else %} Nueva {% endif %} Sub-Categoria </div>
                            <div class="dropdown-divider"></div>
                            <!-- <div class="row">
                                <div class="col-5">
                                    <div class="input-group">
                                        <input type="text" name="description" maxlength="100" class="form-control"
                                            required id="id_description" placeholder="Descripciòn"
                                            value="{% if obj %} {{obj.description}} {% endif %}">
                                        {{ form.category }}
                                    </div>
                                </div>
                                <div class="col-5">
                                    <div class="input-group">
                                        <input type="text" name="description" maxlength="100" class="form-control"
                                            required id="id_description" placeholder="Descripciòn"
                                            value="{% if obj %} {{obj.description}} {% endif %}">
                                        {{ form.descripcion }}
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="input-group">
                                        <label for="id_status">Estatus</label>
                                        <input type="checkbox" name="status" class="form-control" id="id_status" 
                                        {% if obj.status %} checked {% endif %}>
                                        {{ form.status }}
                                    </div>
                                </div> -->
                            {{ form.as_p }}
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span
                                        class="fa fa-save"></span>Guardar</button>
                                <a href=" {% url 'inv:subcategories_list' %}" class="btn btn-success"><span
                                        class="fa fa-undo"></span>Cancelar</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock page_content %}

{% block js_page %}
{% endblock js_page %}

inv/templates/inv/subcategory_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-12 col-md-12 mb-12">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
            {% else %}
            <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if obj %} Editar {% else %} Nueva {% endif %} Sub-Categoria </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col-5">
                                    <div class="input-group">
                                        <!-- <input type="text" name="description" maxlength="100" class="form-control"
                                            required id="id_description" placeholder="Descripciòn"
                                            value="{% if obj %} {{obj.description}} {% endif %}"> -->
                                        {{ form.category }}
                                    </div>
                                </div>
                                <div class="col-5">
                                    <div class="input-group">
                                        <!-- <input type="text" name="description" maxlength="100" class="form-control"
                                            required id="id_description" placeholder="Descripciòn"
                                            value="{% if obj %} {{obj.description}} {% endif %}"> -->
                                        {{ form.description }}
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="input-group">
                                        <!-- <label for="id_status">Estatus</label>
                                        <input type="checkbox" name="status" class="form-control" id="id_status" 
                                        {% if obj.status %} checked {% endif %}> -->
                                        {{ form.status }}
                                    </div>
                                </div>
                                <!-- {{ form.as_p }} -->
                            </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col">
                                    <button type="submit" class="btn btn-danger"><span
                                            class="fa fa-save"></span>Guardar</button>
                                    <a href=" {% url 'inv:subcategories_list' %}" class="btn btn-success"><span
                                            class="fa fa-undo"></span>Cancelar</a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
</form>
{% endblock page_content %}

{% block js_page %}
{% endblock js_page %}

inv/templates/inv/um_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-12 col-md-12 mb-12">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
            {% else %}
            <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if obj %} Editar {% else %} Nueva {% endif %} Unidad de Medida </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col-10">
                                    <div class="input-group">
                                        <!-- <input type="text" name="description" maxlength="100" class="form-control"
                                            required id="id_description" placeholder="Descripciòn"
                                            value="{% if obj %} {{obj.description}} {% endif %}"> -->
                                        {{ form.description }}
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="input-group">
                                        <!-- <label for="id_status">Estatus</label>
                                        <input type="checkbox" name="status" class="form-control" id="id_status" 
                                        {% if obj.status %} checked {% endif %}> -->
                                        {{ form.status }}
                                    </div>
                                </div>
                                <!-- {{ form.as_p }} -->
                            </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col">
                                    <button type="submit" class="btn btn-danger"><span
                                            class="fa fa-save"></span>Guardar</button>
                                    <a href=" {% url 'inv:um_list' %}" class="btn btn-success"><span
                                            class="fa fa-undo"></span>Cancelar</a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
</form>
{% endblock page_content %}

{% block js_page %}
{% endblock js_page %}